version: '3.7'
services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: docker
      target: dev
    volumes:
      - .:/app
    links:
      - php-fpm:php-fpm
    expose:
      - 9000
    ports:
      - 80:80
  php-fpm:
    build:
      dockerfile: php-fpm/Dockerfile
      context: docker
      target: dev
    expose:
      - 9000
    volumes:
      - .:/app
