apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "k8s-symfony-example.fullname" . }}
    labels:
        app: {{ template "k8s-symfony-example.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
data:
    nginx.conf: |-
        server {
            listen 0.0.0.0:80;
            server_name localhost;
            root /app/public;

            location / {
                try_files $uri /index.php$is_args$args;
            }

            location ~ ^/index\.php(/|$) {
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                fastcgi_param DOCUMENT_ROOT $realpath_root;
                internal;
            }

            error_log /var/log/nginx/project_error.log;
            access_log /var/log/nginx/project_access.log;
        }
